FactoryBot.define do
  factory :stakeholder do
    name { Faker::Name.name }
    email { Faker::Internet.email }
    company { association :company }
    status { :invited }
    
    # invitation_token will be auto-generated by the model callback
    
    trait :with_long_name do
      name { "#{Faker::Name.first_name} #{Faker::Name.last_name} #{Faker::Name.suffix}" }
    end
    

    
    trait :assessment_completed do
      status { :assessment_completed }
      
      after(:create) do |stakeholder|
        create(:assessment, stakeholder: stakeholder, completed_at: 1.hour.ago)
      end
    end
    
    trait :with_custom_token do
      after(:build) do |stakeholder|
        stakeholder.invitation_token = SecureRandom.uuid
      end
    end
    
    trait :for_tech_company do
      association :company, :tech_company
      name { "#{Faker::Name.first_name} #{Faker::Name.last_name}" }
      email { Faker::Internet.email(domain: 'techcorp.com') }
    end
    
    trait :for_consulting_company do
      association :company, :consulting_company
      name { "#{Faker::Name.first_name} #{Faker::Name.last_name}" }
      email { Faker::Internet.email(domain: 'consulting.com') }
    end
  end
end
